/bin/sh: 1: root: not found
/usr/local/bin/python: No module named main
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/app/main.py", line 145, in <module>
    main()  # Exécute le pipeline de mise à jour
    ^^^^^^
  File "/app/main.py", line 93, in main
    subprocess.run(["python", "/app/services/1_maj_meteo.py"], check=True)
  File "/usr/local/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.11/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'python'
=== 1) Mise à jour des données météo ===
